Stardome/Controllers/ProducerController.cs
using Stardome.DomainObjects;
using Stardome.Repositories;
using Stardome.Services.Domain;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;


namespace Stardome.Controllers
{
    
    
    public class ProducerController : Controller
    {
        //
        // GET: /Producer/
       

        private IUserAuthCredentialService userAuthCredentialService;
        private IRoleService roleService;
        public ActionResult Index()
        {
            userAuthCredentialService = new UserAuthCredentialService(new UserAuthCredentialRepository(new StardomeEntitiesCS()));
            roleService = new RoleService(new RoleRepository(new StardomeEntitiesCS()));

            if (ModelState.IsValid && WebSecurity.IsAuthenticated)
            {

                int roleId = userAuthCredentialService.GetByUsername(WebSecurity.CurrentUserName).Role.Id;
                if (roleId != 2)
                    return (new AccountController()).RedirectToLocal(roleId);
                else
                {
                    ViewBag.showAdminMenu = false;
                    return View();
                }
            }
            else
            {
                ViewBag.showAdminMenu = false;
                return View();
            }

        }

     
        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> files, string selectPath)
        {
            List<string> results = new List<string>();
            var allowedExtensions = new[] { ".doc", ".mp3", ".txt", ".jpeg" };
            var uploadedFiles = 0;
            var existingFiles = 0;
            var incorrectFiles = 0;
            foreach (var file in files) {
                if (file != null && file.ContentLength > 0)
                {
                    var extension = Path.GetExtension(file.FileName);
                    if (!allowedExtensions.Contains(extension))
                    {
                        //ViewBag.Message = "Incorrect file type";
                        //Files with an extension that we don't allow, won't be uploaded
                        ++incorrectFiles;
                    }


                    else try
                        {   //Upload files to the folder TestUploads. If the folder doesn't exist, it creates it.
                            string filePath = selectPath;
                            bool exists = System.IO.Directory.Exists(Server.MapPath(filePath));
                            if (!exists) { System.IO.Directory.CreateDirectory(Server.MapPath(filePath)); }
                            string path = Path.Combine(Server.MapPath(filePath),
                                                       Path.GetFileName(file.FileName));
                            if (!System.IO.File.Exists(path))
                            {
                                file.SaveAs(path);
                                //ViewBag.Message = "File uploaded successfully";
                                ++uploadedFiles;
                            }
                            else
                            {
                                //ViewBag.Message = "At least 1 file already exists. Please rename it to upload it.";
                                ++existingFiles;
                            }

                        }
                        catch (Exception ex)
                        {
                            ViewBag.Message = "ERROR:" + ex.Message.ToString();
                        }
                }}
                //else Testing without Else
                //{
                   // ViewBag.Message = "You have not specified any files.";
                //}
            if (existingFiles > 0)
            {
                if (existingFiles == 1)
                    //ViewBag.Existing = "1 file already exists. Please rename it.";
                    results.Add(String.Format("1 file already exists. Please rename it."));
                else
                    //ViewBag.Existing = existingFiles + " files already exist. Please rename them.";
                    results.Add(String.Format(existingFiles + " files already exist. Please rename them."));
                                     
            }

            if (incorrectFiles > 0)
            {
                if (incorrectFiles == 1)
                    //ViewBag.Incorrect = " 1 file is of the wrong type.";
                    results.Add(String.Format(" 1 file is of the wrong type."));
                else
                    //ViewBag.Incorrect = incorrectFiles + " files are of the wrong type.";
                    results.Add(String.Format(incorrectFiles + " files are of the wrong type."));
            }

            if (uploadedFiles == 1)
                //ViewBag.Uploaded = " 1 file uploaded successfully.";
            results.Add(String.Format(" 1 file uploaded successfully."));
            else
                //ViewBag.Uploaded = uploadedFiles + " files uploaded successfully.";
                results.Add(String.Format(uploadedFiles + " files uploaded successfully."));
            //string[] resultArray = results.ToArray();
            //ViewBag.Results = resultArray;
             
            //return View();
            ViewBag.Message = "Uploading to " + selectPath;
            return View(results);
        }

        public ActionResult Upload()
        {
            List<string> results = new List<string>();
            ViewBag.showAdminMenu = false;
            return View(results);



        }

      }
}

Stardome/Views/Producer/Upload.cshtml

@Scripts.Render("~/Scripts/jsTree")
@Styles.Render("~/Content/jsTree")
@if (Request.IsAuthenticated == false)
{
    Response.Redirect("~/Account/Login");

}

@{
    ViewBag.Title = "Upload";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Message</h1>
            </hgroup>

        </div>
    </section>
}
<html>

<head>
    <meta charset="utf-8">
    <title>jsTree test</title>

    <script type="text/javascript">
        var path = 'C:/Users/';
        function openFile(file) {
            window.location = file;
        }
        $(document).ready(function () {
            $('#MainTree').fileTree({
                root: 'C:/Users/',
                script: '../Scripts/jqueryFileTree.aspx'
            }, function (file) {
                openFile(file);
            }); 
        });
    </script>

</head>
<body>
    <h2>Files</h2>
    <div id="MainTree"></div>
    

    @using (Html.BeginForm("Upload", "Producer", new { selectPath = "~/TestUploads" },
    FormMethod.Post, new { enctype = "multipart/form-data", }))
    {
        <label for="file">Upload File</label>
        <input type="file" name="files" multiple="multiple" /><br><br>
        <input type="submit" value="Upload Selected Files" /><br>
        @ViewBag.Message<br>
       
    }
    

    <!-- Replace #'s with AT symbol -->
    @model List<string>
    @foreach (var element in Model)
    {
        <p>@Html.DisplayFor(m => element)</p>
    } 

    <!--#foreach (string results in ViewBag.Results)
    {
        #Html.Label(results)
        <br />
    } -->

</body>
</html>  
